name: Java CI with Maven (Push)

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: JIRAID
          server-password: JIRAPASS
          gpg-private-key: ${{ secrets.GPGKEYNAME }}
          gpg-passphrase: GPG_SIGNING_KEY

      - name: Build with Maven
        run: mvn -B compile --file pom-maven-central.xml

      - name: Publish to Maven Central Packages
        run: mvn -DskipTests --file pom-maven-central.xml deploy -Dgpg.passphrase=${{ secrets.GPG_SIGNING_KEY }}
        env:
          OSSRH_USERNAME: ${{ secrets.JIRAID }}
          OSSRH_PASSWORD: ${{ secrets.JIRAPASS }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY }}